import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';

// Sitemaps are generated by `scripts/generate-sitemap.js` (run as part of the
// build). The Astro sitemap integration was removed because it produced an
// unreferenced duplicate set of files in dist/, and its serialize() patterns
// (which all matched `/foo/` with trailing slash) were dead under
// `trailingSlash: 'never'`.

export default defineConfig({
  site: 'https://www.digistorms.ai',
  // Canonical URL form is no-trailing-slash. Astro emits dist/foo/index.html
  // (default `build.format: 'directory'`); Vercel's `cleanUrls: true` +
  // `trailingSlash: false` (vercel.json) serves it at `/foo` and 308-redirects
  // any `/foo/` request to `/foo`.
  trailingSlash: 'never',
  integrations: [
    react(),
    tailwind({ applyBaseStyles: false }),
  ],
  vite: {
    resolve: {
      alias: { '@': '/src' },
    },
  },
});
