export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  shortDescription: string;
  date: string;
  readTime: string;
  thumbnail?: string;
  heroImage?: string;
  /** Library tag slugs used to surface related email examples at the bottom of the article */
  libraryTags?: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "net-revenue-retention",
    title: "Understanding net revenue retention and its formula",
    description:
      "Master net revenue retention (NRR) to drive SaaS growth! Learn calculation methods, key strategies, and industry benchmarks for sustainable success.",
    shortDescription: "Unlock key net revenue retention strategies to boost growth and reduce churn.",
    date: "2026-04-03",
    readTime: "11 min read",
    thumbnail: "/blog/net-revenue-retention/banner.webp",
    heroImage: "/blog/net-revenue-retention/banner.webp",
  },
  {
    slug: "user-engagement-strategy",
    title: "User engagement strategy: 10 ways to boost retention in 2026",
    description:
      "Discover 10 effective user engagement strategies to boost retention, reduce churn, and grow your SaaS. A comprehensive guide to mastering user engagement.",
    shortDescription: "Learn how to create a user engagement strategy that reduces churn and increases loyalty.",
    date: "2026-04-03",
    readTime: "16 min read",
    thumbnail: "/blog/user-engagement-strategy/banner.webp",
    heroImage: "/blog/user-engagement-strategy/banner.webp",
  },
  {
    slug: "aha-moment-examples",
    title: "8 Aha moment examples from top SaaS companies",
    description:
      "Discover 8 real-world Aha moment examples from top SaaS companies and learn how to identify, measure, and optimize your product's Aha moment for success.",
    shortDescription: "Discover 8 real-world Aha moments in SaaS and learn how to guide users to retention.",
    date: "2026-04-03",
    readTime: "18 min read",
    thumbnail: "/blog/aha-moment-examples/banner.webp",
    heroImage: "/blog/aha-moment-examples/banner.webp",
  },
  {
    slug: "product-led-growth-vs-sales-led-growth",
    title: "Product led growth vs sales led growth: Which is right?",
    description:
      "Discover the key differences between product led growth vs sales led growth, and find the best strategy for your SaaS business with our detailed comparison.",
    shortDescription: "Compare product led and sales led growth to find the right strategy for your business.",
    date: "2026-04-03",
    readTime: "14 min read",
    thumbnail: "/blog/product-led-growth-vs-sales-led-growth/banner.webp",
    heroImage: "/blog/product-led-growth-vs-sales-led-growth/banner.webp",
  },
  {
    slug: "saas-onboarding-checklist",
    title: "The ultimate SaaS onboarding checklist",
    description:
      "Use this SaaS onboarding checklist to optimize user experience, boost retention, and streamline the onboarding process for lasting user engagement.",
    shortDescription: "A comprehensive guide to improve SaaS onboarding and retain users for the long term.",
    date: "2026-04-03",
    readTime: "20 min read",
    thumbnail: "/blog/saas-onboarding-checklist/banner.webp",
    heroImage: "/blog/saas-onboarding-checklist/banner.webp",
  },
  {
    slug: "gross-churn-vs-net-churn",
    title: "Gross churn vs net churn in SaaS: what matters?",
    description:
      "Learn how gross churn vs net churn can reduce churn and lead to negative churn, where expansion revenue exceeds losses, driving customer retention and growth.",
    shortDescription: "Understand how churn metrics impact revenue and help drive long-term business growth.",
    date: "2026-04-03",
    readTime: "11 min read",
    thumbnail: "/blog/gross-churn-vs-net-churn/banner.webp",
    heroImage: "/blog/gross-churn-vs-net-churn/banner.webp",
  },
  {
    slug: "product-led-growth-vs-marketing-led-growth",
    title: "Product-led growth vs marketing-led growth - Comparison Guide",
    description:
      "Discover why product-led growth vs marketing-led growth isn't really an honest debate, and learn how marketing supports both PLG and SLG models.",
    shortDescription: "See how marketing fits into PLG and SLG strategies without leading the charge.",
    date: "2026-04-03",
    readTime: "11 min read",
    thumbnail: "/blog/product-led-growth-vs-marketing-led-growth/banner.webp",
    heroImage: "/blog/product-led-growth-vs-marketing-led-growth/banner.webp",
  },
  {
    slug: "saas-gamification",
    title: "10 SaaS gamification examples for user engagement in 2026",
    description:
      "Boost user engagement and loyalty with these SaaS gamification techniques, illustrated with examples from some of the best companies in the SaaS industry.",
    shortDescription: "Discover gamification tactics to make your product more fun to use and reduce churn.",
    date: "2026-04-03",
    readTime: "16 min read",
    thumbnail: "/blog/saas-gamification/banner.webp",
    heroImage: "/blog/saas-gamification/banner.webp",
  },
  {
    slug: "average-customer-retention-rate-saas",
    title: "Average customer retention rate SaaS: Are you on track?",
    description:
      "Learn what the average customer retention rate SaaS companies should aim for, key metrics to track, and strategies to improve loyalty and reduce churn.",
    shortDescription: "Discover essential metrics and strategies to boost customer retention in SaaS.",
    date: "2026-04-03",
    readTime: "14 min read",
    thumbnail: "/blog/average-customer-retention-rate-saas/banner.webp",
    heroImage: "/blog/average-customer-retention-rate-saas/banner.webp",
  },
  {
    slug: "product-led-growth-flywheel",
    title: "Building a successful product-led growth flywheel",
    description:
      "Learn how to build a product-led growth flywheel to drive scalable growth. Boost acquisition, activation, retention, and advocacy for your SaaS success",
    shortDescription: "Build a growth flywheel where your product powers acquisition, retention, and advocacy.",
    date: "2026-04-03",
    readTime: "18 min read",
    thumbnail: "/blog/product-led-growth-flywheel/banner.webp",
    heroImage: "/blog/product-led-growth-flywheel/banner.webp",
  },
  {
    slug: "product-led-growth-metrics",
    title: "7 product-led growth metrics to track your PLG strategy",
    description:
      "Discover 7 essential product-led growth metrics to refine your PLG strategy and drive SaaS success. Track the numbers that matter most for sustainable growth.",
    shortDescription: "Track key metrics like NRR and TTV to refine your product-led growth strategy.",
    date: "2026-04-03",
    readTime: "20 min read",
    thumbnail: "/blog/product-led-growth-metrics/banner.webp",
    heroImage: "/blog/product-led-growth-metrics/banner.webp",
  },
  {
    slug: "saas-welcome-email",
    title: "SaaS welcome email: best practices with 28 examples",
    description: "Build a winning SaaS welcome email! Discover best practices, timing tips, real-life examples and behavior-based ideas to level up your onboarding experience.",
    shortDescription: "Get expert tips to craft welcome emails that wow users and kickstart product engagement!",
    date: "2026-03-23",
    readTime: "12 min read",
    thumbnail: "/blog/saas-welcome-email/banner.webp",
    heroImage: "/blog/saas-welcome-email/banner.webp",
    libraryTags: ["welcome-free-users", "welcome-paid-users"],
  },
  {
    slug: "product-launch-email",
    title: "Product launch email: best practices with 23 examples",
    description: "Discover what makes a great product launch email for SaaS. See real examples, proven strategies, and templates to boost engagement and conversions.",
    shortDescription: "Explore 23 standout emails and tips to nail your next big product launch.",
    date: "2026-03-15",
    readTime: "10 min read",
    thumbnail: "/blog/product-launch-email/banner.webp",
    heroImage: "/blog/product-launch-email/banner.webp",
    libraryTags: ["product-update", "feature-update", "new-feature-nudge"],
  },
  {
    slug: "saas-newsletter",
    title: "SaaS newsletter: best practices with 15 examples",
    description: "Explore how to craft a standout SaaS newsletter and build engagement with best practices, strategy tips, and 15 real life examples from top SaaS companies.",
    shortDescription: "Learn what makes a great newsletter with 15 SaaS examples that actually work.",
    date: "2026-03-01",
    readTime: "9 min read",
    thumbnail: "/blog/saas-newsletter/banner.webp",
    heroImage: "/blog/saas-newsletter/banner.webp",
    libraryTags: ["newsletter"],
  },
  {
    slug: "webinar-email-sequence",
    title: "Webinar email sequence: best practices with 25 examples",
    description: "Learn how to craft a high-converting webinar email sequence with proven strategies, timing tips, and real-life examples to boost signups and engagement.",
    shortDescription: "Want more webinar signups and engagement? Here's how your emails can deliver big.",
    date: "2026-03-23",
    readTime: "11 min read",
    thumbnail: "/blog/webinar-email-sequence/banner.webp",
    heroImage: "/blog/webinar-email-sequence/banner.webp",
    libraryTags: ["webinar-invitation", "webinar-confirmation"],
  },
  {
    slug: "webinar-follow-up-email",
    title: "Webinar follow up email: best practices with 13 examples",
    description: "Explore how to write an effective webinar follow up email with 13 real examples, smart segmentation, and tips to drive leads, clicks, and next steps.",
    shortDescription: "Get 13 follow-up email examples and tips to boost engagement after your next webinar.",
    date: "2026-02-15",
    readTime: "8 min read",
    thumbnail: "/blog/webinar-follow-up-email/banner.webp",
    heroImage: "/blog/webinar-follow-up-email/banner.webp",
    libraryTags: ["webinar-recording", "follow-up"],
  },
  {
    slug: "webinar-emails",
    title: "Webinar emails: best practices with 20 examples",
    description: "Learn how to craft high-converting webinar emails with best practices and 20 real examples from top B2B SaaS brands to boost attendance and engagement.",
    shortDescription: "See how top brands write compelling emails that drive signups, clicks, and webinar buzz.",
    date: "2026-02-01",
    readTime: "9 min read",
    thumbnail: "/blog/webinar-emails/banner.webp",
    heroImage: "/blog/webinar-emails/banner.webp",
    libraryTags: ["webinar-invitation", "webinar-confirmation", "webinar-recording"],
  },
  {
    slug: "milestone-emails",
    title: "Milestone emails: best practices with 12 examples",
    description: "Learn how to create a milestone email that drives engagement. Discover best practices, real SaaS examples, and tips to automate your customer success.",
    shortDescription: "Make milestone emails your secret weapon for better SaaS engagement and retention.",
    date: "2026-01-20",
    readTime: "8 min read",
    thumbnail: "/blog/milestone-emails/banner.webp",
    heroImage: "/blog/milestone-emails/banner.webp",
    libraryTags: ["milestone-reached", "usage-summary", "year-in-review"],
  },
  {
    slug: "upgrade-emails",
    title: "Upgrade emails: best practices with 13 examples",
    description: "Learn how to write upgrade emails that convert trial users into paying customers. Includes timing tips, best practices, and examples from top SaaS companies.",
    shortDescription: "Turn free users into customers with pro tips and examples from top companies.",
    date: "2026-01-15",
    readTime: "9 min read",
    thumbnail: "/blog/upgrade-emails/banner.webp",
    heroImage: "/blog/upgrade-emails/banner.webp",
    libraryTags: ["upgrade-cta", "trial-expired-upgrade", "trial-expiration-warning"],
  },
  {
    slug: "dunning-emails",
    title: "8 Dunning emails: best practices with 8 examples",
    description: "Learn how to write a dunning email that recovers failed payments, reduces churn, and keeps your customer relationships intact with these tips and examples.",
    shortDescription: "Real tips and examples to turn failed payments into recovered revenue—fast.",
    date: "2025-03-28",
    readTime: "7 min read",
    thumbnail: "/blog/dunning-emails/banner.webp",
    heroImage: "/blog/dunning-emails/banner.webp",
    libraryTags: ["payment-declined", "payment-reminder", "billing-reminder"],
  },
];
