export interface FormField {
  key: string;
  label: string;
  type: string;
  placeholder: string;
  required: boolean;
  sublabel?: string;
  options?: Array<{ value: string; label: string }>;
}

export const FORM_FIELDS: Record<string, FormField> = {
  companyName: {
    key: "companyName",
    label: "What's your company URL?",
    type: "text",
    placeholder: "e.g., myapp.com",
    required: true,
  },
  senderName: {
    key: "senderName",
    label: "Your name",
    type: "text",
    placeholder: "e.g. Alex — appears in From and signature",
    required: true,
  },
  popularFeature: {
    key: "popularFeature",
    label: "Do you want to highlight any popular use case or feature?",
    type: "text",
    placeholder: "Real-time dashboards",
    required: true,
  },
  keyOutcome: {
    key: "keyOutcome",
    label: "What's the key outcome you want trial users to achieve?",
    type: "text",
    placeholder: "Publish their first report",
    required: true,
  },
  supportOffered: {
    key: "supportOffered",
    label: "Should we include links to docs, call, templates, or guides?",
    type: "text",
    placeholder: "e.g., Link to help center, setup guide, template gallery",
    required: false,
  },
  destinationUrl: {
    key: "destinationUrl",
    label: "CTA: Link destination",
    type: "text",
    placeholder: "e.g. https://yourapp.com",
    required: true,
  },
  primaryAction: {
    key: "primaryAction",
    label: "What's the #1 action you want new users to take?",
    type: "text",
    placeholder: "e.g., Create their first dashboard",
    required: true,
  },
  failingAction: {
    key: "failingAction",
    label: "What action are users failing to complete?",
    type: "text",
    placeholder: "Finish workspace setup",
    required: true,
  },
  benefitUnlocked: {
    key: "benefitUnlocked",
    label: "What benefit is unlocked by completing the action?",
    type: "text",
    placeholder: "Unlock team collaboration and reporting",
    required: true,
  },
  milestoneTrigger: {
    key: "milestoneTrigger",
    label: "What milestone triggers this email (e.g. first project created)?",
    type: "text",
    placeholder: "User created their first project",
    required: true,
  },
  nextStep: {
    key: "nextStep",
    label: "What should be the next step?",
    type: "text",
    placeholder: "Share their first project",
    required: true,
  },
  caseStudyTestimonial: {
    key: "caseStudyTestimonial",
    label: "Do you want to highlight any case study or testimonial?",
    type: "text",
    placeholder: "Link to case study or insert testimonial",
    required: true,
  },
  notificationTiming: {
    key: "notificationTiming",
    label: "When should this notification be sent?",
    type: "select",
    placeholder: "",
    required: true,
    options: [
      { value: "48-hours-before", label: "48 hours before ending" },
      { value: "24-hours-before", label: "24 hours before ending" },
      { value: "time-of-ending", label: "Time of ending" },
    ],
    sublabel: "We recommend two notifications: One before the ending and one when it ends.",
  },
  accessLoss: {
    key: "accessLoss",
    label: "Should we remind them of what they'll lose access to?",
    type: "text",
    placeholder: "Access to saved projects and analytics",
    required: true,
  },
  recommendedPlan: {
    key: "recommendedPlan",
    label: "What plan do you want to recommend?",
    type: "text",
    placeholder: "Starter plan",
    required: true,
  },
  enticementOffer: {
    key: "enticementOffer",
    label: "Do you want to offer anything to entice return (e.g. trial extension)?",
    type: "text",
    placeholder: "Offer a 7-day trial extension",
    required: true,
  },
  mainTheme: {
    key: "mainTheme",
    label: "What's the main theme: education, trust-building, updates?",
    type: "text",
    placeholder: "Product tips, feature update and case study",
    required: true,
  },
  featureUpdates: {
    key: "featureUpdates",
    label: "Any feature updates they missed that should be highlighted?",
    type: "text",
    placeholder: "Our new dashboard UX",
    required: true,
  },
  firstValueMoment: {
    key: "firstValueMoment",
    label: "What's the first value moment your paid users should reach?",
    type: "text",
    placeholder: "Collaborate with their team",
    required: true,
  },
  powerFeatureTip: {
    key: "powerFeatureTip",
    label: "Do you want to showcase a power feature or advanced tip?",
    type: "text",
    placeholder: "Our new report dashboard",
    required: true,
  },
  newPlan: {
    key: "newPlan",
    label: "What new plan did they upgrade to (e.g. Pro, Team, Scale)?",
    type: "text",
    placeholder: "Pro plan",
    required: true,
  },
  nextAction: {
    key: "nextAction",
    label: "What action should they take next to get the most out of the upgrade?",
    type: "text",
    placeholder: "Connect to Google Sheets",
    required: true,
  },
  featureName: {
    key: "featureName",
    label: "What feature or tip should we highlight?",
    type: "text",
    placeholder: "Keyboard shortcuts",
    required: true,
  },
  featureValue: {
    key: "featureValue",
    label: "What value does it provide?",
    type: "text",
    placeholder: "Save 10 hours per week",
    required: true,
  },
  supportType: {
    key: "supportType",
    label: "What kind of support are you offering?",
    type: "text",
    placeholder: "Free onboarding call, migration help, premium support",
    required: true,
  },
  supportCTA: {
    key: "supportCTA",
    label: "What should they do to access support?",
    type: "text",
    placeholder: "Book a call, reply to this email, check our help center",
    required: true,
  },
  surveyType: {
    key: "surveyType",
    label: "What type of survey?",
    type: "select",
    placeholder: "",
    required: true,
    options: [
      { value: "nps", label: "NPS (0-10 scale)" },
      { value: "csat", label: "CSAT (satisfaction rating)" },
      { value: "ces", label: "CES (effort score)" },
    ],
  },
  surveyIncentive: {
    key: "surveyIncentive",
    label: "Any incentive for completing the survey?",
    type: "text",
    placeholder: "Enter to win $100 Amazon gift card",
    required: false,
  },
  reviewPlatform: {
    key: "reviewPlatform",
    label: "Where should they leave a review?",
    type: "text",
    placeholder: "G2, Capterra, Product Hunt, App Store",
    required: true,
  },
  reviewIncentive: {
    key: "reviewIncentive",
    label: "Any incentive for leaving a review?",
    type: "text",
    placeholder: "Free month of Pro, $25 gift card, exclusive swag",
    required: false,
  },
  newFeature: {
    key: "newFeature",
    label: "What's the new feature?",
    type: "text",
    placeholder: "AI-powered analytics dashboard",
    required: true,
  },
  featureBenefit: {
    key: "featureBenefit",
    label: "What problem does it solve or benefit does it provide?",
    type: "text",
    placeholder: "Get insights 10x faster",
    required: true,
  },
  launchDate: {
    key: "launchDate",
    label: "When was it launched or when will it be available?",
    type: "text",
    placeholder: "Available now, launching next week",
    required: true,
  },
  upsellFeature: {
    key: "upsellFeature",
    label: "What feature or plan are you upselling?",
    type: "text",
    placeholder: "Team plan with advanced analytics",
    required: true,
  },
  upsellBenefit: {
    key: "upsellBenefit",
    label: "What's the key benefit?",
    type: "text",
    placeholder: "Collaborate with unlimited team members",
    required: true,
  },
  pricingDetails: {
    key: "pricingDetails",
    label: "Any pricing details to mention?",
    type: "text",
    placeholder: "$49/month, special upgrade discount available",
    required: false,
  },
  annualDiscount: {
    key: "annualDiscount",
    label: "What discount or benefit for annual billing?",
    type: "text",
    placeholder: "Save 20%, 2 months free",
    required: true,
  },
  annualValue: {
    key: "annualValue",
    label: "What's the value proposition?",
    type: "text",
    placeholder: "Lock in current pricing, reduce billing headaches",
    required: true,
  },
  currentUsage: {
    key: "currentUsage",
    label: "What usage metric are they approaching?",
    type: "text",
    placeholder: "API calls, storage, team members",
    required: true,
  },
  usageThreshold: {
    key: "usageThreshold",
    label: "What's the threshold or limit?",
    type: "text",
    placeholder: "90% of 10,000 API calls",
    required: true,
  },
  upgradeOption: {
    key: "upgradeOption",
    label: "What's the upgrade option?",
    type: "text",
    placeholder: "Pro plan with 100,000 API calls",
    required: true,
  },
  limitHit: {
    key: "limitHit",
    label: "What limit did they hit?",
    type: "text",
    placeholder: "Maximum team members, storage cap, API rate limit",
    required: true,
  },
  impactDescription: {
    key: "impactDescription",
    label: "How does this impact them?",
    type: "text",
    placeholder: "Can't invite new team members, can't upload more files",
    required: true,
  },
  lockedFeature: {
    key: "lockedFeature",
    label: "What feature is locked?",
    type: "text",
    placeholder: "Advanced analytics, custom branding, SSO",
    required: true,
  },
  featureTeaser: {
    key: "featureTeaser",
    label: "Why is this feature valuable?",
    type: "text",
    placeholder: "Make data-driven decisions faster",
    required: true,
  },
  unlockPath: {
    key: "unlockPath",
    label: "How can they unlock it?",
    type: "text",
    placeholder: "Upgrade to Pro plan",
    required: true,
  },
  detractorConcern: {
    key: "detractorConcern",
    label: "What concern or pain point should we address?",
    type: "text",
    placeholder: "Pricing, missing features, support quality",
    required: true,
  },
  improvementAction: {
    key: "improvementAction",
    label: "What are you doing to improve?",
    type: "text",
    placeholder: "Building requested features, improving support response times",
    required: true,
  },
  issueDescription: {
    key: "issueDescription",
    label: "What issue or problem occurred?",
    type: "text",
    placeholder: "Service outage, billing error, feature bug",
    required: true,
  },
  resolutionAction: {
    key: "resolutionAction",
    label: "What are you doing to make it right?",
    type: "text",
    placeholder: "Account credit, free month, dedicated support",
    required: true,
  },
  paymentIssue: {
    key: "paymentIssue",
    label: "What payment issue occurred?",
    type: "text",
    placeholder: "Card declined, expired card, insufficient funds",
    required: true,
  },
  paymentDeadline: {
    key: "paymentDeadline",
    label: "When will service be interrupted?",
    type: "text",
    placeholder: "In 3 days, in 7 days",
    required: true,
  },
  cancellationReason: {
    key: "cancellationReason",
    label: "Common reasons users cancel (if known)?",
    type: "text",
    placeholder: "Too expensive, missing features, not using enough",
    required: false,
  },
  retentionOffer: {
    key: "retentionOffer",
    label: "What can you offer to prevent cancellation?",
    type: "text",
    placeholder: "50% discount for 3 months, downgrade option, personalized setup help",
    required: true,
  },
  downgradeReason: {
    key: "downgradeReason",
    label: "Do you want to ask why they downgraded?",
    type: "text",
    placeholder: "Yes - include feedback survey link",
    required: false,
  },
  retainedValue: {
    key: "retainedValue",
    label: "What value do they still have access to?",
    type: "text",
    placeholder: "Core features, limited team members, basic analytics",
    required: true,
  },
  cancellationFeedback: {
    key: "cancellationFeedback",
    label: "Do you want to request feedback?",
    type: "text",
    placeholder: "Yes - link to exit survey",
    required: false,
  },
  winbackOffer: {
    key: "winbackOffer",
    label: "What's your winback offer or hook?",
    type: "text",
    placeholder: "New features, 30% discount, free migration help",
    required: true,
  },
  timeSinceChurn: {
    key: "timeSinceChurn",
    label: "How long since they churned?",
    type: "text",
    placeholder: "3 months, 6 months, 1 year",
    required: false,
  },
  inviterName: {
    key: "inviterName",
    label: "Who sent the invitation?",
    type: "text",
    placeholder: "Dynamic - from your system",
    required: true,
  },
  teamBenefit: {
    key: "teamBenefit",
    label: "What's the benefit of having this new team member?",
    type: "text",
    placeholder: "Better collaboration, shared workspace, team analytics",
    required: true,
  },
  referralIncentive: {
    key: "referralIncentive",
    label: "What's the referral incentive?",
    type: "text",
    placeholder: "Both get 1 month free, $50 credit each, free upgrade",
    required: true,
  },
  referralProcess: {
    key: "referralProcess",
    label: "How do they refer someone?",
    type: "text",
    placeholder: "Share unique link, send email invite from dashboard",
    required: true,
  },
  communityPlatform: {
    key: "communityPlatform",
    label: "What platform is your community on?",
    type: "text",
    placeholder: "Slack, Discord, Circle, LinkedIn Group",
    required: true,
  },
  communityValue: {
    key: "communityValue",
    label: "What value will they get from joining?",
    type: "text",
    placeholder: "Get help from users, networking, early feature access",
    required: true,
  },
  feedbackTopic: {
    key: "feedbackTopic",
    label: "What do you want feedback on?",
    type: "text",
    placeholder: "Feature priorities, pain points, roadmap input",
    required: true,
  },
  feedbackIncentive: {
    key: "feedbackIncentive",
    label: "Any incentive for providing feedback?",
    type: "text",
    placeholder: "Early access to features, $25 gift card, exclusive swag",
    required: false,
  },
  betaFeature: {
    key: "betaFeature",
    label: "What beta feature or program?",
    type: "text",
    placeholder: "AI assistant, new dashboard, mobile app",
    required: true,
  },
  betaRequirements: {
    key: "betaRequirements",
    label: "Any requirements or expectations for beta testers?",
    type: "text",
    placeholder: "Provide weekly feedback, commit to 30-day test period",
    required: false,
  },
  webinarTopic: {
    key: "webinarTopic",
    label: "What's the webinar topic?",
    type: "text",
    placeholder: "Advanced analytics strategies, product roadmap reveal",
    required: true,
  },
  webinarDate: {
    key: "webinarDate",
    label: "When is the webinar?",
    type: "text",
    placeholder: "Thursday, March 15 at 2pm EST",
    required: true,
  },
  webinarSpeaker: {
    key: "webinarSpeaker",
    label: "Who's presenting?",
    type: "text",
    placeholder: "CEO, product team, industry expert",
    required: false,
  },
  articleTopic: {
    key: "articleTopic",
    label: "What's the article topic?",
    type: "text",
    placeholder: "10 ways to improve team productivity",
    required: true,
  },
  articleValue: {
    key: "articleValue",
    label: "Why should they read it?",
    type: "text",
    placeholder: "Learn best practices, save time, avoid common mistakes",
    required: true,
  },
  contentType: {
    key: "contentType",
    label: "What type of content?",
    type: "text",
    placeholder: "Ultimate guide, industry report, ebook, template library",
    required: true,
  },
  contentBenefit: {
    key: "contentBenefit",
    label: "What will they learn or gain?",
    type: "text",
    placeholder: "Complete framework for..., industry benchmarks, ready-to-use templates",
    required: true,
  },
  caseStudyCustomer: {
    key: "caseStudyCustomer",
    label: "Which customer or company?",
    type: "text",
    placeholder: "Acme Corp, TechStart Inc",
    required: true,
  },
  caseStudyResult: {
    key: "caseStudyResult",
    label: "What results did they achieve?",
    type: "text",
    placeholder: "3x revenue growth, 50% time savings, 10x faster deployment",
    required: true,
  },
  growthMetric: {
    key: "growthMetric",
    label: "What growth milestone?",
    type: "text",
    placeholder: "10,000 customers, $10M ARR, Series B funding",
    required: true,
  },
  growthImpact: {
    key: "growthImpact",
    label: "How does this benefit users?",
    type: "text",
    placeholder: "More resources for features, better stability, longer runway",
    required: true,
  },
  pressMention: {
    key: "pressMention",
    label: "What press mention or award?",
    type: "text",
    placeholder: "Featured in TechCrunch, won Best SaaS award",
    required: true,
  },
  credibilityBoost: {
    key: "credibilityBoost",
    label: "Why does this matter to users?",
    type: "text",
    placeholder: "Industry validation, proven solution, trusted by leaders",
    required: true,
  },
};
